all: orbit.ps 

FILES=orbit/CVS \
      orbit/Makefile* \
      orbit/stylesheet-images/CVS \
      orbit/stylesheet-images/Makefile*

orbit.ps: orbit.xml
	db2ps orbit.xml
	db2pdf orbit.xml
	tar czvf cvs.tar.gz $(FILES)
	db2html orbit.xml 
	tar xzvf cvs.tar.gz
	cp orbit/index.html orbit/book1.html
