
all:
	$(MAKE) -C echo         all 
	$(MAKE) -C calculator   all
	$(MAKE) -C account      all
	$(MAKE) -C byteseq      all
	$(MAKE) -C badcall      all
	$(MAKE) -C factory  	all
	$(MAKE) -C name-resolve all
	$(MAKE) -C callback     all
	$(MAKE) -C threaded-calculator   all

clean:
	rm -f *~
	$(MAKE) -C echo         clean
	$(MAKE) -C calculator   clean
	$(MAKE) -C account      clean
	$(MAKE) -C byteseq      clean
	$(MAKE) -C badcall      clean
	$(MAKE) -C factory      clean
	$(MAKE) -C name-resolve clean
	$(MAKE) -C callback     clean
	$(MAKE) -C threaded-calculator   clean

distclean: 
	rm -f *~
	$(MAKE) -C echo         distclean
	$(MAKE) -C calculator   distclean
	$(MAKE) -C account      distclean
	$(MAKE) -C byteseq      distclean
	$(MAKE) -C badcall      distclean
	$(MAKE) -C factory      distclean
	$(MAKE) -C name-resolve distclean
	$(MAKE) -C callback     distclean
	$(MAKE) -C threaded-calculator   distclean

