#!/usr/bin/perl -w
use strict;

#Fairly simple;
#Just read in the directory.  Each file we care about is
#  in the following format:
#    gnumeric-version

if(!defined($ARGV[0])){
  print STDERR "No argument given!  What directory should I create an index in?!\n";
  exit 1;
}
my $maindir=shift(@ARGV);

#Alright.  Open the directory.
opendir(DIR, $maindir) or die("Unable to open directory \"$maindir\"!  ($!).\n");

#First, output to the header.
print <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Gnumeric Release Announcements</title>
    <meta name="GENERATOR" content="Emacs and perl"/>
    <meta name="Use" content="Mozilla!"/>
    <meta name="contains" content="only 47.2% of the gross kludges compared to the
 leading web pages!">
    <style type="text/css">
     <!--
        html {
         height: 100%;
         width: 100%;
        }
        body {
         height: 100%;
         width: 100%;
         background: #F0F0F0;
        }
      -->
    </style>
  </head>
  <body>
    <div>
    <ul>
EOF
;

my $dir;
my $tmp;
my @pieces;
my $modded = 0;
while($dir = readdir(DIR)){
  if($dir eq "." || $dir eq ".."){next;}
  #Make sure it's in the proper format.
  if(!($dir =~ /^gnumeric-[0-9]+\.[0-9]+\.[0-9]+(\.html|\.shtml)*$/)){next;}
  #Trim off any .html
  $tmp = $dir;
  $tmp =~ s/\.[a-zA-Z]*$//g;
  #Alright.  It is.  Now, output our links.
  @pieces = split(/-+/, $tmp);
  print "      <li><a href=\"$dir\">$pieces[1]</a></i>\n";
  $modded=1;
}
if(!$modded){
  print "      <li>No announcements yet!  Check back later.</li>\n";
}

#Now output the footer.
print <<EOF
    </ul>
    </div>
  </body>
</html>
EOF
;
