/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl badcall.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "badcall.h"

/*** App-specific servant structures ***/

typedef struct
{
   POA_Examples_BadCall servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   CORBA_long counter;
   /* ------ ---------- end ------------ ------ */
} impl_POA_Examples_BadCall;

/*** Implementation stub prototypes ***/

static void impl_Examples_BadCall__destroy(impl_POA_Examples_BadCall *
					   servant, CORBA_Environment * ev);

static Examples_BadCall_Foo
impl_Examples_BadCall_trigger(impl_POA_Examples_BadCall * servant,
			      const CORBA_long val,
			      Examples_BadCall_Foo * bar,
			      CORBA_Environment * ev);

/*** epv structures ***/

static PortableServer_ServantBase__epv impl_Examples_BadCall_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Examples_BadCall__destroy,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Examples_BadCall__epv impl_Examples_BadCall_epv = {
   NULL,			/* _private */

   (gpointer) & impl_Examples_BadCall_trigger,

};

/*** vepv structures ***/

static POA_Examples_BadCall__vepv impl_Examples_BadCall_vepv = {
   &impl_Examples_BadCall_base_epv,
   &impl_Examples_BadCall_epv,
};

/*** Stub implementations ***/

static Examples_BadCall
impl_Examples_BadCall__create(PortableServer_POA poa, CORBA_Environment * ev)
{
   Examples_BadCall retval;
   impl_POA_Examples_BadCall *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Examples_BadCall, 1);
   newservant->servant.vepv = &impl_Examples_BadCall_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);
   POA_Examples_BadCall__init((PortableServer_Servant) newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */ 
   newservant->counter=0;  /* init */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

static void
impl_Examples_BadCall__destroy(impl_POA_Examples_BadCall * servant,
			       CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */ 
   servant->counter=0;  /* reset */
   /* ------ ---------- end ------------- ------ */

   POA_Examples_BadCall__fini((PortableServer_Servant) servant, ev);
}

static Examples_BadCall_Foo
impl_Examples_BadCall_trigger(impl_POA_Examples_BadCall * servant,
			      const CORBA_long val,
			      Examples_BadCall_Foo * bar,
			      CORBA_Environment * ev)
{
   Examples_BadCall_Foo ret_val = {0.0};


   /* ------   insert method code here   ------ */
   switch ((servant->counter++) % 3)
   {
   case 0:
   {
	   Examples_BadCall_Foo dummy_foo = {0.0};

	   /* FIXME, define ownership */
           CORBA_exception_set (ev, 
				CORBA_USER_EXCEPTION,
                                ex_Examples_BadCall_NoParam,
                                NULL); /* exception has no members */
 	   *bar=dummy_foo; 
           return dummy_foo;
           break;
   }
   case 1:
   case 2:
   {
	   Examples_BadCall_Foo dummy_foo = {0.0};

	   Examples_BadCall_SingleParam* ex_param
		   = Examples_BadCall_SingleParam__alloc();
	   ex_param->mesg = CORBA_string_dup ("describing the problem for client");

	   /* FIXME, define ownership */
           CORBA_exception_set (ev, 
				CORBA_USER_EXCEPTION,
                                ex_Examples_BadCall_SingleParam,
                                ex_param); /* exception has members */
 	   *bar=dummy_foo; 
           return dummy_foo;
           break;
   }
   default:
           g_assert_not_reached ();
   }
   /* ------ ---------- end ------------ ------ */

   return ret_val;
}
