
module Examples {

	interface BadCall {
		struct Foo { 
			double fval; 
		};

		exception NoParam     { };
		exception SingleParam { string mesg; };
		exception DoubleParam { string mesg; long val; };

		Foo trigger (in long val, out Foo bar) 
			raises (NoParam, SingleParam, DoubleParam);
	};
};
