/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl badcall.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "badcall.h"

/*** App-specific servant structures ***/

typedef struct
{
   POA_Examples_BadCall servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   CORBA_long counter;
   /* ------ ---------- end ------------ ------ */
} impl_POA_Examples_BadCall;

/*** Implementation stub prototypes ***/

static void impl_Examples_BadCall__fini(impl_POA_Examples_BadCall *
					servant, CORBA_Environment * ev);

static Examples_BadCall_Foo
impl_Examples_BadCall_trigger(impl_POA_Examples_BadCall * servant,
			      const CORBA_long val,
			      Examples_BadCall_Foo * bar,
			      CORBA_Environment * ev);

/*** epv structures ***/

static PortableServer_ServantBase__epv impl_Examples_BadCall_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Examples_BadCall__fini,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Examples_BadCall__epv impl_Examples_BadCall_epv = {
   NULL,			/* _private */

   (gpointer) & impl_Examples_BadCall_trigger,

};

/*** vepv structures ***/

static POA_Examples_BadCall__vepv impl_Examples_BadCall_vepv = {
   &impl_Examples_BadCall_base_epv,
   &impl_Examples_BadCall_epv,
};

/*** Stub implementations ***/

static Examples_BadCall
impl_Examples_BadCall__create(PortableServer_POA poa, CORBA_Environment * ev)
{
   Examples_BadCall retval;
   impl_POA_Examples_BadCall *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Examples_BadCall, 1);
   newservant->servant.vepv = &impl_Examples_BadCall_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);
   POA_Examples_BadCall__init((PortableServer_Servant) newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */ 
   newservant->counter=0;  /* init */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

static void
impl_Examples_BadCall__fini (impl_POA_Examples_BadCall * servant,
			     CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */ 
   servant->counter=0;  /* reset */
   /* ------ ---------- end ------------- ------ */

   POA_Examples_BadCall__fini((PortableServer_Servant) servant, ev);
   
   g_free (servant);
}

static Examples_BadCall_Foo
impl_Examples_BadCall_trigger(impl_POA_Examples_BadCall * servant,
			      const CORBA_long val,
			      Examples_BadCall_Foo * bar,
			      CORBA_Environment * ev)
{
   Examples_BadCall_Foo ret_val = {0.0};


   /* ------   insert method code here   ------ */
   switch ((servant->counter++) % 2)
   {
   case 0:
   {
	   /* this piece of code demonstrates how to raise exception
	    * without any further parameter */

	   Examples_BadCall_Foo dummy_foo = {0.0};

	   /* after user has assinged exception attributes, user may
	    * not touch the data anymore, ownership is handed over to
	    * CORBA environment  */
           CORBA_exception_set (ev, 
				CORBA_USER_EXCEPTION,
                                ex_Examples_BadCall_NoParam,
                                NULL); /* exception has no members */

 	   /* on exception you need not to care about out-argument
	    * @bar, but due to programming language C it is necessary
	    * to return valid value */ 
           return dummy_foo;
           break;
   }
   case 1:
   {
	   /* this piece of code demonstrates how to raise exception
	    * that has a string as parameter */

	   Examples_BadCall_Foo dummy_foo = {0.0};

	   Examples_BadCall_SingleParam* ex_parameters
		   = Examples_BadCall_SingleParam__alloc();

	   ex_parameters->mesg 
		   = CORBA_string_dup ("raised in \"" __FILE__ "\"");

	   /* after user has assinged exception attributes, user may
	    * not touch the data anymore, ownership is handed over to
	    * CORBA environment  */
           CORBA_exception_set (ev, 
				CORBA_USER_EXCEPTION,
                                ex_Examples_BadCall_SingleParam,
                                ex_parameters); /* exception has members */

 	   /* on exception you need not to care about out-argument
	    * @bar, but due to programming language C it is necessary
	    * to return valid value */ 
           return dummy_foo;
           break;
   }
   /* this code will never raise exception DoubleParam */

   default:
           g_assert_not_reached ();
   }
   /* ------ ---------- end ------------ ------ */

   return ret_val;
}
