/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl name-resolve.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "name-resolve.h"

/*** App-specific servant structures ***/

typedef struct
{
   POA_Examples_NameResolve_Service servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_Examples_NameResolve_Service;

/*** Implementation stub prototypes ***/

static void
impl_Examples_NameResolve_Service__fini(impl_POA_Examples_NameResolve_Service
					* servant, CORBA_Environment * ev);
static void
impl_Examples_NameResolve_Service_echoString
(impl_POA_Examples_NameResolve_Service * servant, const CORBA_char * input,
CORBA_Environment * ev);

/*** epv structures ***/

static PortableServer_ServantBase__epv
   impl_Examples_NameResolve_Service_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Examples_NameResolve_Service__fini,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Examples_NameResolve_Service__epv
   impl_Examples_NameResolve_Service_epv = {
   NULL,			/* _private */
   (gpointer) & impl_Examples_NameResolve_Service_echoString,

};

/*** vepv structures ***/

static POA_Examples_NameResolve_Service__vepv
   impl_Examples_NameResolve_Service_vepv = {
   &impl_Examples_NameResolve_Service_base_epv,
   &impl_Examples_NameResolve_Service_epv,
};

/*** Stub implementations ***/

static Examples_NameResolve_Service
impl_Examples_NameResolve_Service__create(PortableServer_POA poa,
					  CORBA_Environment * ev)
{
   Examples_NameResolve_Service retval;
   impl_POA_Examples_NameResolve_Service *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Examples_NameResolve_Service, 1);
   newservant->servant.vepv = &impl_Examples_NameResolve_Service_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);

   POA_Examples_NameResolve_Service__init((PortableServer_Servant) newservant,
					  ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

/**
 * impl_Examples_NameResolve_Service__fini
 * 
 * Destructor called after servant has been deactivated finally.
 * In case any active operation invocation, method call is being delayed.
 * Note, in former versions of ORBit2 this function would have been
 * named impl_Examples_NameResolve_Service__destroy.
**/
static void
impl_Examples_NameResolve_Service__fini(impl_POA_Examples_NameResolve_Service
					* servant, CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   POA_Examples_NameResolve_Service__fini((PortableServer_Servant) servant,
					  ev);

   g_free(servant);
}

static void
impl_Examples_NameResolve_Service_echoString
   (impl_POA_Examples_NameResolve_Service * servant, const CORBA_char * input,
    CORBA_Environment * ev)
{
   /* ------   insert method code here   ------ */
   g_print (">> %s\n", input);
   /* ------ ---------- end ------------ ------ */
}
