// MyFirstOrbit program - The Account object

#include <callback-server.idl>

module Callback {
	/* inherit from Callback::Client */ 
	interface ClientEx : Callback::Client {
		void update_ex (in long num, in long ex);
	};

};
