
all:
	$(MAKE) -C echo       all 
	$(MAKE) -C calculator all
	$(MAKE) -C account    all
	$(MAKE) -C byteseq    all

clean:
	$(MAKE) -C echo       clean
	$(MAKE) -C calculator clean
	$(MAKE) -C account    clean
	$(MAKE) -C byteseq    clean

distclean:
	$(MAKE) -C echo       distclean
	$(MAKE) -C calculator distclean
	$(MAKE) -C account    distclean
	$(MAKE) -C byteseq    distclean
