
all:
	$(MAKE) -C echo       all 
	$(MAKE) -C calculator all
	$(MAKE) -C account    all
	$(MAKE) -C byteseq    all
	$(MAKE) -C badcall    all

clean:
	$(MAKE) -C echo       clean
	$(MAKE) -C calculator clean
	$(MAKE) -C account    clean
	$(MAKE) -C byteseq    clean
	$(MAKE) -C badcall    clean

distclean:
	$(MAKE) -C echo       distclean
	$(MAKE) -C calculator distclean
	$(MAKE) -C account    distclean
	$(MAKE) -C byteseq    distclean
	$(MAKE) -C badcall    distclean
