
module Examples {

	module Factory {

		interface AbstractService {
			void doit (in string mesg);
			void destroy ();
		};

		interface Producer {
			AbstractService produce (in string id);
		};
	};
};
