/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl callback-client.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "callback-client.h"

/*** App-specific servant structures ***/

typedef struct
{
   POA_Callback_Client servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_Callback_Client;

typedef struct
{
   POA_Callback_Server servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_Callback_Server;

typedef struct
{
   POA_Callback_ClientEx servant;
   PortableServer_POA poa;

   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_Callback_ClientEx;

/*** Implementation stub prototypes ***/

static void impl_Callback_Client__destroy(impl_POA_Callback_Client * servant,
					  CORBA_Environment * ev);
static void
impl_Callback_Client_update(impl_POA_Callback_Client * servant,
			    const CORBA_long num, CORBA_Environment * ev);

static void impl_Callback_Server__destroy(impl_POA_Callback_Server * servant,
					  CORBA_Environment * ev);
static void
impl_Callback_Server_register_client(impl_POA_Callback_Server * servant,
				     const Callback_Client cb,
				     CORBA_Environment * ev);

static void impl_Callback_ClientEx__destroy(impl_POA_Callback_ClientEx *
					    servant, CORBA_Environment * ev);
static void impl_Callback_ClientEx_update_ex(impl_POA_Callback_ClientEx *
					     servant, const CORBA_long num,
					     const CORBA_long ex,
					     CORBA_Environment * ev);

static void
impl_Callback_ClientEx_update(impl_POA_Callback_ClientEx * servant,
			      const CORBA_long num, CORBA_Environment * ev);

/*** epv structures ***/

static PortableServer_ServantBase__epv impl_Callback_Client_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Callback_Client__destroy,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Callback_Client__epv impl_Callback_Client_epv = {
   NULL,			/* _private */
   (gpointer) & impl_Callback_Client_update,

};
static PortableServer_ServantBase__epv impl_Callback_Server_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Callback_Server__destroy,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Callback_Server__epv impl_Callback_Server_epv = {
   NULL,			/* _private */
   (gpointer) & impl_Callback_Server_register_client,

};

static PortableServer_ServantBase__epv impl_Callback_ClientEx_base_epv = {
   NULL,			/* _private data */
   (gpointer) & impl_Callback_ClientEx__destroy,	/* finalize routine */
   NULL,			/* default_POA routine */
};
static POA_Callback_ClientEx__epv impl_Callback_ClientEx_epv = {
   NULL,			/* _private */
   (gpointer) & impl_Callback_ClientEx_update_ex,

};
static POA_Callback_Client__epv impl_Callback_ClientEx_Callback_Client_epv = {
   NULL,			/* _private */
   (gpointer) & impl_Callback_ClientEx_update,
};

/*** vepv structures ***/

static POA_Callback_Client__vepv impl_Callback_Client_vepv = {
   &impl_Callback_Client_base_epv,
   &impl_Callback_Client_epv,
};
static POA_Callback_Server__vepv impl_Callback_Server_vepv = {
   &impl_Callback_Server_base_epv,
   &impl_Callback_Server_epv,
};

static POA_Callback_ClientEx__vepv impl_Callback_ClientEx_vepv = {
   &impl_Callback_ClientEx_base_epv,
   &impl_Callback_ClientEx_Callback_Client_epv,
   &impl_Callback_ClientEx_epv,
};

/*** Stub implementations ***/

static Callback_Client
impl_Callback_Client__create(PortableServer_POA poa, CORBA_Environment * ev)
{
   Callback_Client retval;
   impl_POA_Callback_Client *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Callback_Client, 1);
   newservant->servant.vepv = &impl_Callback_Client_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);
   POA_Callback_Client__init((PortableServer_Servant) newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

static void
impl_Callback_Client__destroy(impl_POA_Callback_Client * servant,
			      CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   POA_Callback_Client__fini((PortableServer_Servant) servant, ev);

   g_free(servant);
}

static void
impl_Callback_Client_update(impl_POA_Callback_Client * servant,
			    const CORBA_long num, CORBA_Environment * ev)
{
   /* ------   insert method code here   ------ */
   /* ------ ---------- end ------------ ------ */
}

static Callback_Server
impl_Callback_Server__create(PortableServer_POA poa, CORBA_Environment * ev)
{
   Callback_Server retval;
   impl_POA_Callback_Server *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Callback_Server, 1);
   newservant->servant.vepv = &impl_Callback_Server_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);
   POA_Callback_Server__init((PortableServer_Servant) newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

static void
impl_Callback_Server__destroy(impl_POA_Callback_Server * servant,
			      CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   POA_Callback_Server__fini((PortableServer_Servant) servant, ev);

   g_free(servant);
}

static void
impl_Callback_Server_register_client(impl_POA_Callback_Server * servant,
				     const Callback_Client cb,
				     CORBA_Environment * ev)
{
   /* ------   insert method code here   ------ */
   /* ------ ---------- end ------------ ------ */
}

static Callback_ClientEx
impl_Callback_ClientEx__create(PortableServer_POA poa, CORBA_Environment * ev)
{
   Callback_ClientEx retval;
   impl_POA_Callback_ClientEx *newservant;
   PortableServer_ObjectId *objid;

   newservant = g_new0(impl_POA_Callback_ClientEx, 1);
   newservant->servant.vepv = &impl_Callback_ClientEx_vepv;
   newservant->poa =
      (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object) poa, ev);
   POA_Callback_ClientEx__init((PortableServer_Servant) newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   objid = PortableServer_POA_activate_object(poa, newservant, ev);
   CORBA_free(objid);
   retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

   return retval;
}

static void
impl_Callback_ClientEx__destroy(impl_POA_Callback_ClientEx * servant,
				CORBA_Environment * ev)
{
   CORBA_Object_release((CORBA_Object) servant->poa, ev);

   /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

   POA_Callback_ClientEx__fini((PortableServer_Servant) servant, ev);

   g_free(servant);
}

static void
impl_Callback_ClientEx_update_ex(impl_POA_Callback_ClientEx * servant,
				 const CORBA_long num,
				 const CORBA_long ex, CORBA_Environment * ev)
{
   /* ------   insert method code here   ------ */
	g_printf ("server invoked update_ex %d %d\n", num, ex);

	/* even on failure - this method does not throw any exception */ 
   /* ------ ---------- end ------------ ------ */
}

static void
impl_Callback_ClientEx_update(impl_POA_Callback_ClientEx * servant,
			      const CORBA_long num, CORBA_Environment * ev)
{
   /* ------   insert method code here   ------ */
	g_printf ("server invoked callback interface: %d\n", num);

	/* even on failure - this method does not throw any exception */ 
   /* ------ ---------- end ------------ ------ */
}
