
all:
	$(MAKE) -C server  	all
	$(MAKE) -C client  	all

clean:
	rm -f *~
	$(MAKE) -C server      	clean
	$(MAKE) -C client	clean

distclean: 
	rm -f *~
	$(MAKE) -C server       distclean
	$(MAKE) -C client   	distclean

