#!/bin/bash

#Update Makefile.am
rm Makefile.am
DIRS=$(find -type d)
echo -e "#This file is generated by snappy.sh\n" >> Makefile.am
echo "urlpath = /snappy/" >> Makefile.am

for D in $DIRS ;
do
    if [ $(find -L $D -maxdepth 1 -type f | grep -v .svn | sed -e "s:^..::g" | wc -l) -ne 0 ]; then
        if [ "." != $D ]; then
            FILES=$(find -L $D -maxdepth 1 -type f | grep -v .svn | sed -e "s:^..::g" | xargs echo)
            DIR_NAME=$(echo $D | sed -e "s:\.::g" | sed -e "s:/:_:g")
            echo -n "web$DIR_NAME" >> Makefile.am
            echo "dir = \$(pagedir)/$(echo $D | sed -e "s:^..::g")" >> Makefile.am
            echo -n "web$DIR_NAME" >> Makefile.am
            echo "_DATA = $FILES" >> Makefile.am
            echo -e "\n" >> Makefile.am
        else
	    FILES=$(find -L $D -maxdepth 1 -type f | grep -v .svn | sed -e "s:^..::g" | xargs echo)
            DIR_NAME=$(echo $D | sed -e "s:\.::g" | sed -e "s:/:_:g")
            echo -n "page" >> Makefile.am
            echo "_DATA = $FILES" >> Makefile.am 
            echo -e "\n" >> Makefile.am
	fi
    fi

done

echo "include \$(top_srcdir)/rules.common" >> Makefile.am
#End Update Makefile.am



