#!/bin/sh
DOCTYPE='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'

DOCTAG=$(grep '<document' $1)
TITLE=$(echo $DOCTAG | sed 's,.*title=\"\([^\"]*\).*,\1,')
IMGREL=$(echo $DOCTAG | sed 's,.*imgrel=\"\([^\"]*\).*,\1,')
CHANGED=$(grep '<set-last-changed' $1 | sed 's,.*"\(.*\)".*,\1,')

cat <<-HEAD
$DOCTYPE
<html>

<head>
	<title>$TITLE</title>
	<meta name="cvsdate" content="$CHANGED">
</head>

<body>
HEAD

sed "1,/<content/d;/<\/content/,//d" $1

cat <<-FOOT
</body>

</html>
FOOT
