#!/bin/sh
PAGE=$1
ROOT=$2
URLPATH=$3

## we use two seds in these operations so the second
## instance operates on the output of the first, ugh

cat <<HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link href="/css/layout.css" rel="stylesheet" type="text/css" media="screen">
  <link href="/css/style.css" rel="stylesheet" type="text/css" media="all">
  <link rel="icon" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
  <link rel="SHORTCUT ICON" type="image/png" href="http://www.gnome.org/img/logo/foot-16.png">
HTML

## CONTENTS OF <HEAD>
sed -e "s#\(</\?\(head\|body\)[^>]*>\)#\n\1\n#g" $PAGE | \
sed -e "1,/<head>/d" \
	-e "/<\/head>/,\$d"

## SUCK OUT H1
HEADING=$(sed -e "s#\(</\?h1[^>]*>\)#\n\1\n#g" $PAGE | \
sed -e "1,/<h1>/d" \
	-e "/<\/h1>/,\$d")

## END OF <HEAD> AND HEADER
cat <<HEAD
</head>

<body>
  <!-- site header -->
  <div id="page">
    <ul id="general">
      <li id="siteaction-gnome_home" class="home">
        <a href="http://www.gnome.org/" title="Home">Home</a>
      </li>
      <li id="siteaction-gnome_news">
        <a href="http://news.gnome.org/" title="News">News</a>
      </li>
      <li id="siteaction-gnome_projects">
        <a href="http://www.gnome.org/projects/" title="Projects">Projects</a>
      </li>
      <li id="siteaction-gnome_art">
        <a href="http://art.gnome.org/" title="Art">Art</a>
      </li>
      <li id="siteaction-gnome_support">
        <a href="http://www.gnome.org/support/" title="Support">Support</a>
      </li>
      <li id="siteaction-gnome_development">
        <a href="http://developer.gnome.org/" title="Development">Development</a>
      </li>
      <li id="siteaction-gnome_community">
        <a href="http://www.gnome.org/community/" title="Community">Community</a>
      </li>
    </ul>
    <div id="header">
      <h1>$HEADING</h1>
      <!--
      <div id="tabs">
        <ul id="portal-globalnav">
          <li id="portaltab-root" class="selected">
            <a href="/"><span>Home</span></a>
          </li>
          <li><a href=""><span></span></a></li>
          <li><a href=""><span></span></a></li>
        </ul>
      </div> <!-- end of #tabs -->
      -->
    </div> <!-- end of #header -->
  </div>
<!-- end site header -->

  <div class="body">
    <div id="content">
HEAD

## PAGE CONTENT
sed -e "s#\(</\?\(head\|body\|h1\)[^>]*>\)#\n\1\n#g" $PAGE | \
sed -e "1,/<body>/d" \
	-e "/<h1>/,/<\/h1>/d" \
	-e "/<\/body>/,//d"

## END OF CONTENT AND FOOTER
cat <<FOOT
  </div> <!-- end of content -->

  <div id="footer">
    Copyright &copy; 2005-2007 <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
    <a href="http://validator.w3.org/check/referer">Optimised</a> for <a href="http://www.w3.org/">standards</a>. Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
  </div>

  </div> <!-- end of div.body -->
</body>
</html>
FOOT
