#!/bin/sh
PAGE=$1
ROOT=$2

sed "s,<head>,<head><link rel=\"stylesheet\" type=\"text/css\" href=\"$ROOT/default.css\" /><link rel=\"icon\" type=\"image/png\" href=\"$ROOT/img/logo/foot-16.png\" />,i;s,<body[^>]*>,<body><div id=\"body\">,i;/<\/body>/,//d" $PAGE

cat <<-FOOT
</div>

<div id="sidebar">
	<p class="section">Users</p>
	<ul>
		<li><b><a href="$ROOT/about/">What is GNOME?</a></b></li>
		<li><a href="$ROOT/start/stable/">Download</a></li>
		<!--<li><a href="$ROOT/start/">Get Involved!</a></li>-->
		<li><a href="http://www.gnomedesktop.org/">Community News</a></li>
		<li><a href="$ROOT/softwaremap/">Software Map</a></li>
		<li><a href="http://foundation.gnome.org/">Foundation</a></li>
		<li><a href="$ROOT/press/">Press</a></li>
		<li><a href="$ROOT/contact/">Contact</a></li>
	</ul>
	
	<p class="section">Developers</p>
	<ul>
		<li><a href="http://developer.gnome.org/">Developer Site</a></li>
		<li><a href="http://mail.gnome.org/">Mailing Lists</a></li>
		<li><a href="http://bugzilla.gnome.org/">Bugzilla</a></li>
		<li><a href="http://cvs.gnome.org/lxr/">LXR</a></li>
		<li><a href="http://cvs.gnome.org/bonsai/">Bonsai</a></li>
	</ul>
</div>

<div id="hdr">
	<div id="logo"><a href="$ROOT/"><img src="$ROOT/img/spacer" alt="Home" /></a></div>
	<div id="banner"><img src="$ROOT/img/spacer" alt="" /></div>
	<p class="none"></p>
	<div id="hdrNav">
		<a href="http://www.gnome.org/about/">About GNOME</a> &middot;
		<a href="http://www.gnome.org/start/stable/">Download</a> &middot;
		<!--<a href="http://www.gnome.org/start/"><i>Get Involved!</i></a> &middot;-->
		<a href="http://www.gnome.org/"><b>Users</b></a> &middot;
		<a href="http://developer.gnome.org/">Developers</a> &middot;
		<a href="http://foundation.gnome.org/">Foundation</a> &middot;
		<a href="http://www.gnome.org/contact/">Contact</a>
	</div>
</div>

<div id="copyright">
Copyright &copy; 2003, <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
<a href="http://validator.w3.org/check/referer">Optimised</a> for
<a href="http://www.w3.org/">standards</a>.
Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
</div>

</body>

</html>
FOOT
