#!/bin/sh
PAGE=$1
ROOT=$2
URLPATH=$3

sed "s,<head>,<head><link rel=\"stylesheet\" type=\"text/css\" href=\"/default.css\" /><link rel=\"icon\" type=\"image/png\" href=\"/img/logo/foot-16.png\" />,i;s,<body[^>]*>,<body><div id=\"body\">,i;/<\/body>/,//d" $PAGE

cat <<-FOOT
</div>

<div id="sidebar">
	<p class="section">Users</p>
	<ul>
		<li><b><a href="/about/">What is GNOME?</a></b></li>
		<li><a href="/start/stable/">Download</a></li>
		<!--<li><a href="/start/">Get Involved!</a></li>-->
		<li><a href="http://www.gnomedesktop.org/">Community News</a></li>
		<li><a href="/softwaremap/">Software Map</a></li>
		<li><a href="http://foundation.gnome.org/">Foundation</a></li>
		<li><a href="/press/">Press</a></li>
		<li><a href="/contact/">Contact</a></li>
	</ul>
	
	<p class="section">Developers</p>
	<ul>
		<li><a href="http://developer.gnome.org/">Developer Site</a></li>
		<li><a href="http://mail.gnome.org/">Mailing Lists</a></li>
		<li><a href="http://bugzilla.gnome.org/">Bugzilla</a></li>
		<li><a href="http://svn.gnome.org/">Subversion</a></li>
	</ul>
</div>

<div id="hdr">
	<div id="logo"><a href="/"><img src="/img/spacer" alt="Home" /></a></div>
	<div id="banner"><img src="/img/spacer" alt="" /></div>
	<p class="none"></p>
	<div id="hdrNav">
FOOT

LINKS='
		<a href="/about/">About GNOME</a> &middot;
		<a href="/start/stable/">Download</a> &middot;
		<a href="/support/">Support</a> &middot;
		<a href="/community/">Community</a> &middot;
		<a href="http://developer.gnome.org/">Developers</a> &middot;
		<a href="http://foundation.gnome.org/">Foundation</a> &middot;
		<a href="/contact/">Contact</a>
'


echo $URLPATH | grep -E 'support|learn|tour' > /dev/null
SUPPORT=$?
echo $URLPATH | grep -E 'start' > /dev/null
DOWNLOAD=$?
echo $URLPATH | grep -E 'contact|press' > /dev/null
CONTACT=$?
echo $URLPATH | grep -E 'about' > /dev/null
ABOUT=$?
echo $URLPATH | grep -E 'community' > /dev/null
COMMUNITY=$?



if [ $SUPPORT == 0 ]; then
	LINKS=`echo $LINKS | sed 's/Support/<b>Support<\/b>/'`
elif [ $DOWNLOAD == 0 ]; then
	LINKS=`echo $LINKS | sed 's/Download/<b>Download<\/b>/'`
elif [ $CONTACT == 0 ]; then
	LINKS=`echo $LINKS | sed 's/Contact/<b>Contact<\/b>/'`
elif [ $ABOUT == 0 ]; then
	LINKS=`echo $LINKS | sed 's/About GNOME/<b>About GNOME<\/b>/'`
elif [ $COMMUNITY == 0 ]; then
	LINKS=`echo $LINKS | sed 's/Community/<b>Community<\/b>/'`
fi

echo $LINKS

cat <<-FOOT
	</div>
</div>

<div id="copyright">
Copyright &copy; 2007, <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
<a href="http://validator.w3.org/check/referer">Optimised</a> for
<a href="http://www.w3.org/">standards</a>.
Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
</div>

</body>

</html>
FOOT

