<?xml version="1.0"?>

<!-- Generate Rhythmbox web pages
     Copyright © 2003 Colin Walters <walters@rhythmbox.org>

  This file is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
 
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. -->

<xsl:stylesheet id="mkpage" version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="xml" doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
	      doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
	      indent="yes" encoding="UTF-8"/>

  <xsl:template match="/">
    <xsl:text>
    </xsl:text>      
    <xsl:comment> This file is automatically generated by mkpage.xsl.  Do not edit! </xsl:comment>
    <xsl:text>
    </xsl:text>      
    <xsl:apply-templates/>
  </xsl:template>

  <xsl:template match="/page">
    <html>
      <head>
	<title><xsl:value-of select="/page/title"/></title>
	<link href="rb.css" type="text/css" rel="stylesheet"/>
	<link href="rhythmbox-16.png" rel="icon" type="image/png"/>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
      </head>
      <xsl:apply-templates/>
    </html>
  </xsl:template>

  <xsl:template match="/page/title">
  </xsl:template>

  <xsl:template match="body">
    <body>
      <div>
	<img id="headerimg" src="header.png" height="51" width="1013" alt=""/>
      </div>
      <div id="sidebar">
	<p>Navigation</p>
	<ul>
	  <li><a href="index.html">Home</a></li>
	  <li><a href="news.html">News</a></li>
	  <li><a href="screenshots.html">Screenshots</a></li>
	  <li><a href="download.html">Download</a></li>
	  <li><a href="utils.html">Related tools</a></li>
	  <li><a href="http://live.gnome.org/Rhythmbox/FAQ">F.A.Q.</a></li>
	  <li><a href="development.html">Development</a></li>
	  <li><a href="translation.html">Translation</a></li>
	  <li><a href="feedback.html">Feedback</a></li>
	</ul>
      </div>
      <h1><xsl:value-of select="/page/title"/></h1>
      <div id="body">
	<xsl:apply-templates/>
      </div>
      <div class="copyright" id="copyright">
<!-- 	<p> -->
<!-- 	  <a href="http://validator.w3.org/check/referer"> -->
<!-- 	    <img class="button" src="valid-xhtml10.png" alt="Valid XHTML 1.0!" height="31" width="88"/></a> -->
<!-- 	  <a href="http://jigsaw.w3.org/css-validator/"> -->
<!-- 	    <img class="button" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!"/></a> -->
<!-- 	  <a href="http://www.gstreamer.net/"> -->
<!-- 	    <img class="button" src="gstfamily2.png" alt="Part of the GStreamer Family."/></a> -->
<!-- 	  <br/> -->
<!-- 	</p> -->
	<p>
	  Last modified: <xsl:value-of select="$date"/><br/>
	  <!-- Copyright © 2003,2004 <a href="http://web.verbum.org/">Colin Walters</a>.  Available under the <a href="http://creativecommons.org/licenses/sa/1.0/">Creative Commons License</a>.<br/> -->
	  Valid <a href="http://validator.w3.org/check/referer">XHTML</a> and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS 2</a>.<br/>
	</p>
     </div>
    </body>
  </xsl:template>

  <xsl:template match="body/newsitem">
    <div class="newsitem">
      <xsl:apply-templates/>
    </div>
  </xsl:template>

  <xsl:template match="newsitem/title">
    <span class="newshdr">
      <xsl:apply-templates/>
    </span>
    <br/>
  </xsl:template>
      
  <xsl:template match="newsitem/date">
    <span class="newsdate">
      <xsl:apply-templates/>
    </span>
    <br/>
  </xsl:template>

  <xsl:template match="newsitem/body">
    <br/>
    <xsl:apply-templates/>
  </xsl:template>

  <!-- Just pass through all the other elements verbatim. -->
  <xsl:template match="*">
    <xsl:element name="{name()}">
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

</xsl:stylesheet>
      
