all: faq.ps 

FILES=faq/CVS \
      faq/Makefile* \
      faq/stylesheet-images/CVS \
      faq/stylesheet-images/Makefile*

faq.ps: faq.xml
	db2ps faq.xml
	tar czvf cvs.tar.gz $(FILES)	
	db2html -u faq.xml
	tar xzvf cvs.tar.gz


